### ISSUE TITLE
console error and chart is not displayed 

### ISSUE THREAD

**Issue by shahriyar-modami** [wp-statistics/wp-statistics#376] opened 2021-08-31 16:32 UTC
after update to version 13.1 the chart not working.
I checked the console and I have a console error. 
![3333](https://user-images.githubusercontent.com/47687179/131540685-a5527674-9d2c-4448-88b6-ef652ec906a6.JPG)
...
![Capture](https://user-images.githubusercontent.com/47687179/131541660-0295d38d-6ffb-4c33-a36c-b6503ce9333d.JPG)

I flushed the browser cache and deactive other plugin, but it had no effect. 
wp version 5.8
wp-statistics 13.1

**Comment by mostafasoufi** [comment] 2022-10-17 06:57
Hi,

The issue is already fixed in the latest versions. let me know please if you need any further assiatance

**Closed by mostafasoufi** 2022-10-17 06:57 UTC
