### ISSUE TITLE
WordPress database error: Processing the value for the following field failed: uri. The supplied value may be too long or contains invalid data.

### ISSUE THREAD

**Issue by Sinapars** [wp-statistics/wp-statistics#409] opened 2022-08-02 08:19 UTC
Hi Team,
I have been receiving this error continuously since 02-28-2022:
`WordPress database error: Processing the value for the following field failed: uri. The supplied value may be too long or contains invalid data.`

` خطای پایگاه داده وردپرس: پردازش مقدار گزینه‌ زیر ناموفق بود: uri. مقدار ارائه شده ممکن است خیلی طولانی باشد یا حاوی داده‌های نامعتبر باشد.`

WP Statistics: 13.2.5
WP Version: 6.0.1
PHP Version: 7.4.28

BR

**Comment by mostafasoufi** [comment] 2022-08-04 06:40
Hi,

Thank you for reporting the issue, it is highly likely that this error will be resolved by increasing the URI column in its table since the error is quite obvious.

```
ALTER TABLE `wp_statistics_pages` CHANGE `uri` `uri` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;
```
Let me know please how it works.

**Comment by Sinapars** [comment] 2022-08-04 07:34
Hi @mostafasoufi Jan,
This value is currently at **190**!

![image](https://user-images.githubusercontent.com/61265957/182789672-2c9cdd6b-07f2-4632-9abe-44f5a0fdb913.png)

But by default, WordPress allows up to **200 characters** in the URL, so I think changing the number from 190 to 200 will solve this problem.

![image](https://user-images.githubusercontent.com/61265957/182789828-dc176993-c7ed-4858-becf-8d4f389a19f2.png)

Will this problem be fixed in the next update if I don't make a change manually?

BR

**Comment by mostafasoufi** [comment] 2022-08-04 08:14
Please let us know the issue will be solved by leangh 200

**Comment by Sinapars** [comment] 2022-08-04 08:51
sure Mostafa Jan,
I got this error to change the value of this field:
![image](https://user-images.githubusercontent.com/61265957/182805473-b87e882c-b87e-4fac-9967-f8da4068be26.png)

Table Indexes:
![image](https://user-images.githubusercontent.com/61265957/182805610-aa1db2da-383d-4e9a-becc-0dd176cd7dc7.png)

Because the data is very important to me, I don't want to make changes without your coordination and help.
There is also this error with phpMyAdmin

BR

**Comment by mostafasoufi** [comment] 2022-08-05 12:09
You probably need to regenerate the index, do the below work:

1. Make a backup
2. Delete the index: 
```
ALTER TABLE `wp_statistics_pages` DROP INDEX `url`;
```

4. Increase the column length:
```
ALTER TABLE `wp_statistics_pages` CHANGE `uri` `uri` VARCHAR(190) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;
```

5. Add index again:
```
ALTER TABLE `wordpress`.`wp_statistics_pages` ADD UNIQUE `url` (`type`(210));
```

**Comment by Sinapars** [comment] 2022-08-05 15:29
Hi @mostafasoufi Jan,

1. Done

2. Not Done, Because This query : 
` ALTER TABLE 'wp_statistics_pages' DROP INDEX 'url' ;`

- should have been executed for columns **date_2** and **uri** , **until step 4 is done without error**
` ALTER TABLE 'wp_statistics_pages' DROP INDEX 'date_2' ;`
` ALTER TABLE 'wp_statistics_pages' DROP INDEX 'uri' ;`

4. Done, **but** Here too, **200** should be placed instead of **190** :
`ALTER TABLE 'wp_statistics_pages' CHANGE 'uri' 'uri' VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL;`

5. **Not Done**

![image](https://user-images.githubusercontent.com/61265957/183104099-88349ee0-bc6b-43d4-a1c3-47256d9d9e43.png)

[Solution ](Solution):
https://stackoverflow.com/questions/30761867/mysql-error-the-maximum-column-size-is-767-bytes
First should be executed this query for change ROW_FORMAT = COMPACT **to**  **ROW_FORMAT = DYNAMIC**  :

`ALTER TABLE 'dbname'.'wp_statistics_pages' ROW_FORMAT = DYNAMIC;`

and then executed This Querys for add index again:

`ALTER TABLE 'dbname'.'wp_statistics_pages' ADD INDEX 'url'('uri' ASC);`
`ALTER TABLE 'dbname'.'wp_statistics_pages' ADD INDEX 'uri'('uri' ASC, 'count' ASC, 'id' ASC);`
`ALTER TABLE 'dbname'.'wp_statistics_pages' ADD UNIQUE INDEX 'date_2'('uri' ASC, 'date' ASC);`


**I have written all the steps in detail so that you can solve the problem in the next update with less challenge**

My only question is, after these changes, do I need to change ROW_FORMAT to COMPACT again?
I mean step 5
BR

**Comment by Sinapars** [comment] 2022-08-05 16:17
Although all the above things were done well, though the problem is not solved and the error log is still recorded :(

`WordPress database error: Processing the value for the following field failed: uri. The supplied value may be too long or contains invalid data.`

**Comment by mostafasoufi** [comment] 2022-08-17 06:58
> By changing the length of characters from 200 to 210, the problem was solved!

Good to hear! 

> Why? The maximum length of my characters is 200!

Weird indeed and not entirely sure, maybe because of the utf8 strings?

**Comment by Sinapars** [comment] 2022-08-18 07:20
Hi Mostafa Jan,
Yes string is utf8 (Persian character)
Sample string :

`%da%86%d9%87-%d9%81%db%8c%d9%84%d9%85%db%8c-%d8%a8%d8%a8%db%8c%d9%86%d9%85%d8%9f%d8%9b%d8%a8%d8%b1%d8%ae%db%8c-%d8%a7%d9%86%d8%aa%d8%ae%d8%a7%d8%a8%e2%80%8c%d9%87%d8%a7%db%8c-%d8%b3%db%8c%d9%86%d9%85`

But I don't think the problem is with encoding, because this string is inserted in the post table (length 200) without any problem!

**updated:**
The reason why values are correctly inserted in WordPress and in the post table despite the 200 character limit is that WordPress reduces the length of characters that are more than 200 to 199 by default.
![image](https://user-images.githubusercontent.com/61265957/185333729-34e734a6-6ca8-4058-960a-02b782c9beec.png)
I think if you do the same, there is no need to change 200 to 210

BR

**Comment by mostafasoufi** [comment] 2022-08-20 07:18
Good point, will do some tests and make sure all is good.

Thanks!

**Comment by parisaaxp** [comment] 2022-10-30 07:14
Hello everyone

I have the same problem. I get the same error.
and my website is constantly down due to 504 ,.. errors.

I read some of the comments above.
I checked my phpmyadmin and checked uri characters lenghth which was 190.

![db-wp-statistics](https://user-images.githubusercontent.com/60483982/198866722-557cb987-9c7a-4e76-bb2e-261d98893e84.png)

plugin version : 13.2.7
wordpress version : 6.0.3
wp theme : woodmart

I'm gonna deactivate the plugin until I can safely solve the issue with your help.
Sincerely greatful. 🙏

**Comment by mostafasoufi** [comment] 2022-10-30 09:31
Hey @parisaaxp,

Can you please provide us with the error message? also, did you try to increase the column length?

**Comment by parisaaxp** [comment] 2022-10-30 09:58
**[30-Oct-2022 06:05:09 UTC] Failed to insert log entry: خطای پایگاه داده وردپرس: پردازش مقدار گزینه‌ زیر ناموفق بود: url. مقدار ارائه شده ممکن است خیلی طولانی باشد یا حاوی داده‌های نامعتبر باشد.**

I'm new to SQL commands.
I entered "wp_statistics_pages" table.
above I clicked on "edit inline".
first and second step that you have mentioned above has been done successfully.
but at the last step I get this error :

**#1142 - ALTER command denied to user 'cpses_itdjuko0kx'@'localhost' for table 'wp_statistics_pages**

**Comment by mostafasoufi** [comment] 2022-11-01 07:11
Apparently, your Database user doesn't have the privilege to do that, according to this [answer](https://stackoverflow.com/questions/8081394/mysql-wont-let-me-add-column). so, Please grant your user or ask your hosting provider to do that for you. @parisaaxp 

More related issues:
- https://stackoverflow.com/questions/31459925/alter-command-denied-to-user
- https://smartslider.helpscoutdocs.com/article/1994-database-issues

**Comment by Sinapars** [comment] 2023-01-03 21:37
Hi Again,
This ticket is closed but the problem still exists!!
After each update, all the changes we made manually to solve this problem will be lost
BR

**Comment by mostafasoufi** [comment] 2023-01-04 05:46
There was no database update in the latest update. Could you please tell me the changes you make every time you update the system?

**Comment by jghaanstra** [comment] 2023-06-21 08:39
@mostafasoufi

A client of mine is affected by this as well. Having to manually alter the database is no real solution. Especially if it get's reverted on updates. Why was this issue closed?

**Comment by mostafasoufi** [comment] 2023-06-21 12:40
Are you receiving the same issue related to the `uri` datatype? can you please provide me the MySQL error message? @jghaanstra

**Comment by jghaanstra** [comment] 2023-06-21 13:49
> Are you receiving the same issue related to the `uri` datatype? can you please provide me the MySQL error message? @jghaanstra

Here you go:

```
2023/06/21 08:24:04 [error] 107476#107476: *1786675 FastCGI sent in stderr: "PHP message: WP Statistics Error: WordPress database error: Processing the value for the following field failed: uri. The supplied value may be too long or contains invalid data" while reading response header from upstream, client: 90.xxx.xxxx.123, server: clientwebsite.com, request: "GET /wp-json/wp-statistics/v2/hit?wp_statistics_hit_rest=yes&track_all=1&current_page_type=home&current_page_id=24225&search_query&page_uri=Lz91dG1fc291cmNlPWZhY2Vib29rJnV0bV9tZWRpdW09ZGlzcGxheSZ1dG1fY2FtcGFpZ249cWF0YXItYXdhcmVuZXNzLWVmZmljaWVuY3kmZmJjbGlkPUl3QVIxRlF4YW1uM05DVVk0N2dtYjhjYjVMMVB0V29obkMzWEhERXo5a2UyNFlZcnhxVUxGSzdQZWd0NWdfYWVtX3RoX0FZZkM0dUVLNjBndGg0SDNCdmk4UnBDb2RaYXM3NnFwYW9nSmJLODlkYk1RUWhOOE9BbnJ2eWNwajZLX1FrWS04cEZHdndUdGNiS0F3b1AyTlFnSXpSdlk&referred=http%3A%2F%2Fm.facebook.com%2F&_=1687335843717 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.0-fpm-clientwebsite.sock:", host: "clientwebsite.com:61600", referrer: "https://clientwebsite.com/?utm_source=facebook&utm_medium=display&utm_campaign=campaign-source&fbclid=IwAR1FQxamn3NCUY47gmb8cb5L1PtWohnC3XHDEz9ke24YYrxqULFK7Pegt5g_aem_th_AYfC4uEK60gth4H3Bvi8RpCodZas76qpaogJbK89dbMQQhN8OAnrvycpj6K_QkY-8pFGvwTtcbKAwoP2NQgIzRvY"
```

**Comment by mostafasoufi** [comment] 2023-06-23 13:50
Alright, this is much better, I'll ask our development team to work on!

**Comment by jghaanstra** [comment] 2023-06-23 14:02
Affected by this as well. Adding the full log entry, perhaps it helps.

```
2023/06/23 09:52:25 [error] 107476#107476: *1874908 FastCGI sent in stderr: "PHP message: PHP Warning: Attempt to read property "post_type" on null in /wp-content/plugins/wordpress-seo/src/integrations/third-party/elementor.php on line 151" while reading response header from upstream, client: 95.97.251.170, server: clientwebsite.com, request: "POST /wp-admin/admin-ajax.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.0-fpm-clientwebsite.sock:", host: "subdomain.clientwebsite.com:61600", referrer: "https://subdomain.clientwebsite.com/wp-admin/post.php?post=3727&action=elementor"
```

**Comment by mostafasoufi** [comment] 2023-07-19 17:44
Hey folks, the issue is fixed in this commit https://github.com/wp-statistics/wp-statistics/commit/315c962bdb1cb94c5693443afa948c14113bcbff

Best

**Closed by mostafasoufi** 2023-07-19 17:44 UTC
