### ISSUE TITLE
query visitor data by IP address in WP-Statistics

### ISSUE THREAD

**Issue by LiangYongAI** [wp-statistics/wp-statistics#590] opened 2024-11-30 14:39 UTC
![image](https://github.com/user-attachments/assets/7a6c6ab4-cc2f-4080-99bb-ca5f2ca9cc3a)

I write a plugin to use above code to get query visitor data by IP address in WP-Statistics
get the following result
![image](https://github.com/user-attachments/assets/170e9ce9-25f5-40ec-9d4d-70d4254a553d)
I tried serval times ,but some item I concerned is always empty.
[first_view] =>
[first_page] =>
[first_uri] =>

I want to get the fisrt hit time, and how long the user stay in the website.  I use the latest version. How can I do? thanks
@mhdizmni

**Comment by mhdizmni** [comment] 2024-12-01 14:05
Hi @LiangYongAI,

Apologies for the delayed response.

We’re investigating this and will get back to you as soon as possible.

Thanks for your patience!

Regards,
Matthew

**Comment by mhdizmni** [comment] 2024-12-02 08:02
Dear @LiangYongAI,

The issue has been addressed in [this commit](https://github.com/wp-statistics/wp-statistics/commit/b23b4f3a8d789297a31323ebb810c21756155680) and the fix is available in [the development branch](https://github.com/wp-statistics/wp-statistics/tree/development).

Could you please verify if the issue is resolved on your end?

Regards,
Matthew

**Comment by LiangYongAI** [comment] 2024-12-02 15:52
It works, thanks for your soon resolve

**Comment by mhdizmni** [comment] 2024-12-02 20:45
We are glad to be of help!

If you encounter any further issues, feel free to reach out for assistance.

Regards,
Matthew

**Closed by mhdizmni** 2024-12-02 20:45 UTC
