### ISSUE TITLE
WP Statistics plugin - version 14.1 bug

### ISSUE THREAD

**Issue by yllew2** [wp-statistics/wp-statistics#427] opened 2023-05-07 09:07 UTC
I have just installed version 14.1 and it give me a problem on "This plugin failed to load properly and is paused during recovery mode."
Attached is the screenshot error accessing to it.
Please help to resolve the bug for this latest version.
![statistic](https://user-images.githubusercontent.com/65331864/236668406-b9af112d-e8ce-4282-9d8f-a8ebfd6be4ea.JPG)
![statistic2](https://user-images.githubusercontent.com/65331864/236668407-95a05818-c966-4a3d-9c55-a286e35d4424.JPG)

**Comment by mostafasoufi** [comment] 2023-05-07 09:12
Hi,
The issue is already fixed in this commit https://github.com/wp-statistics/wp-statistics/commit/6cced5d724479a2c9296fbf74a843493cd59d9a0 and the new version will be released soon.

**Closed by mostafasoufi** 2023-05-07 09:12 UTC
