### ISSUE TITLE
Hits per Page no longer works

### ISSUE THREAD

**Issue by KillianLeroux** [wp-statistics/wp-statistics#380] opened 2021-09-27 14:40 UTC
Hi!

First of all, thanks for your powerful extension!! ;)

I use WP Statistics for several months and I have noticed since August 16th no data is captured for hits per page :(

I debug and I found a clue in function `Pages::get_page_type()` (file `includes\class-wp-statistics-pages.php`): `get_queried_object_id()` return `0`, and `global $post` is null :/

But when I make `var_dump(get_queried_object_id());` I have `0` in API call `/api/wp-statistics/v2/hit` **3 times** and I have the good value (`75`) **2 times** on frontend, is it normal?

Thanks for your reading :)

**Comment by mostafasoufi** [comment] 2021-09-30 11:11
Hi,

Thank you for opening the issue and your feedback!

That's weird, can you please make sure the what's the value of `current_page_id` in the request?

![Screen Shot 2021-09-30 at 2 08 25 PM](https://user-images.githubusercontent.com/701520/135444691-28e85565-6875-4a55-bf32-5064c2f10bd7.png)

**Comment by KillianLeroux** [comment] 2021-10-17 21:52
Weird indeed :/

I put var_dump in different places, and it appears that it is WP Statistics that loads first:

**Comment by mostafasoufi** [comment] 2021-10-20 08:00
I changed the REST API Prefix by that function through the child-theme, worked fine!

You need just to update the **Permalink** by pressing the **Save Changes** button.

**Comment by KillianLeroux** [comment] 2021-10-20 08:20
Ok so similar to my case... I think I will test on clean installation and add parent theme, child theme and extensions one by one to test.

Yes I already saved Permalink in wp-admin many times ;)

**Comment by KillianLeroux** [comment] 2021-10-20 12:39
And if we put filters in function called after `rest_url_prefix` hook, like that:

```
    /**
     * WP_Statistics Hits Class.
     *
     * @throws \Exception
     */
    public function __construct()
    {
        # Sanitize Hit Data if Has Rest-Api Process
        add_action('rest_url_prefix', array($this, 'hits_init'), 30);

        # Record Login Page Hits
        if (!Option::get('exclude_loginpage')) {
            add_action('init', array($this, 'record_login_page_hits'));
        }

        # Record WordPress Front Page Hits
        add_action('wp', array($this, 'record_wp_hits'), 20);
    }

    public function hits_init()
    {
        if (self::is_rest_hit()) {
            # Get Hit Data
            $this->rest_hits = (object)self::rest_params();

            # Filter Data
            add_filter('wp_statistics_user_agent', array($this, 'set_user_agent'));
            add_filter('wp_statistics_user_referer', array($this, 'set_user_referer'));
            add_filter('wp_statistics_user_ip', array($this, 'set_user_ip'));
            add_filter('wp_statistics_hash_ip', array($this, 'set_hash_ip'));
            add_filter('wp_statistics_exclusion', array($this, 'set_exclusion'));
            add_filter('wp_statistics_user_http_agent', array($this, 'set_user_http_agent'));
            add_filter('wp_statistics_current_timestamp', array($this, 'set_current_timestamp'));
            add_filter('wp_statistics_current_page', array($this, 'set_current_page'));
            add_filter('wp_statistics_page_uri', array($this, 'set_page_uri'));
            add_filter('wp_statistics_user_id', array($this, 'set_user_id'));
            add_filter('wp_statistics_track_all_pages', array($this, 'set_track_all'));
        }
    }
```

?

But I don't understand why it doesn't work for me but it works for you :/

**Comment by dannymasao** [comment] 2021-10-30 04:21
Maybe this is the same issue. After upgrading a site from WordPress 4.9.4 to 5.7 and updating WP statistics along with other plugins, it seems the page hit counting stopped. The hits column in post/pages list for the articles published after the upgrade keeps showing 0. But on the settings page I can see that it tracks overall site visitors/visits. It just stopped tracking individual page hits. Unfortunately, I don't know what version number WP statistics was before I updated it but it probably hadn't been updated in about 2 years. Tried disabling other plugins but doesn't seem like anything changed.

**Comment by craigconstantine** [comment] 2021-10-30 10:54
I've been keeping up with WP and wp-statistics updates within days of every release of both, for years. This just started recently for me. Very oddly, I have 4 other WP sites that use wp-statistics and things are fine on those sites.

On the site with the problem, I recently used a plugin to remove a bunch of [what i believe were] unused tables from the database. So I've been thinking that maybe I removed a table that wp-statistics needs?? I'd expect much more brokenness though...

Can a dev tell me the tables is expects so I can verify I didn't remove one that's needed? …or does it have any sort of "check my tables" functionality built in??

**Comment by KillianLeroux** [comment] 2021-10-30 12:19
I think it's not a db table problem @craigconstantine.

@craigconstantine and @dannymasao do you override the WP API prefix?

The default API prefix is "wp-json" (https://mywebsite.com/wp-json).

For me, it's because I override this API prefix by "api" (https://mywebsite/api) that hit per page doesn't longer work, when I restore "wp-json", it works!

You can override with a plugin, or with use hook "rest_url_prefix" in file "functions.php":
http://hookr.io/4.6/filters/rest_url_prefix/

**Comment by craigconstantine** [comment] 2021-10-31 10:33
http://constantine.name/wp-json/ exists on my server, yes. (So I've not intentionally changed that, and no plugin seems to have changed it.) I notice that "wp-statistics" also appears in the output . . .

I cleared my browser cache and loaded a page on my site. Here's all the resources fetched across the network... I don't see anything in here that indicates j/s making an API call to track a page load . . . am I reading this correctly:

<img width="945" alt="Screen Shot 2021-10-31 at 06 32 26" src="https://user-images.githubusercontent.com/2278992/139578491-100d8885-57e4-44ef-965e-00d068fc08ad.png">

**Comment by craigconstantine** [comment] 2021-10-31 10:38
I'm using the Autoptimize plugin. I have this wp-statistics setting off. Last week I turned this on (and saved the permalinks settings) and I believe that's when I saw the big-fat-zero in my stats for a few days (ref screenshot above) ... ?
<img width="1147" alt="Screen Shot 2021-10-31 at 06 37 41" src="https://user-images.githubusercontent.com/2278992/139578665-5afd24b9-0c26-4219-9e98-f4cb0bdfece6.png">

**Comment by mostafasoufi** [comment] 2021-11-05 12:48
When the **Cache Compatibility option is enabled**, then you can see the REST API request in the Network XHR panel.

If the counter does not work, probably related to a cache issue or REST API endpoint which is blocked or restricted by some security plugin, In terms of experience, It might help to find the issue by checking the following:

- Add the WP-Statistics's REST API endpoint to the whitelist if the REST API is restricted by security plugins or CDNA services such as Cloudflare
- Check the WordPress error log (`WP_DEBUG_LOG`) and WP-Statistics's log which is stored in `wp-content/uplaods/wp-statistics/debug.log`

**Comment by craigconstantine** [comment] 2021-11-15 20:13
` ¯\_(ツ)_/¯  `

I don't have Cache Compat enabled on 4 other WP sites, where "top pages" is showing data. On one of my sites, I've now enabled Cache Compat and I'm seeing "hit" in XHR which looks like it's tracking…

<img width="904" alt="Screen Shot 2021-11-15 at 15 11 37" src="https://user-images.githubusercontent.com/2278992/141847536-70d051cd-2be3-47af-8b78-4d6459b56950.png">

…but still nothing is showing in Top Pages

**Comment by KillianLeroux** [comment] 2021-11-24 13:34
> `¯\_(ツ)_/¯ `
> 
> I don't have Cache Compat enabled on 4 other WP sites, where "top pages" is showing data. On one of my sites, I've now enabled Cache Compat and I'm seeing "hit" in XHR which looks like it's tracking…
> 
> <img alt="Screen Shot 2021-11-15 at 15 11 37" width="904" src="https://user-images.githubusercontent.com/2278992/141847536-70d051cd-2be3-47af-8b78-4d6459b56950.png">
> 
> …but still nothing is showing in Top Pages

I have exactly the same :/
So I developed my own solution :x

**Comment by mostafasoufi** [comment] 2021-11-24 15:38
Weird indeed, can someone give me WordPress access? I think I need to check something there, please send the access to mostafa@veronalabs.com

**Comment by craigconstantine** [comment] 2021-11-25 12:07
I'm not inclined to give you access, no. You're welcome to explain to me how to troubleshoot this. I have full access to the db, wp, etc.

Meanwhile, I'm going to DISable that cache compat feature on this site, since the stats overview now looks like this…

<img width="1382" alt="Screen Shot 2021-11-25 at 07 04 40" src="https://user-images.githubusercontent.com/2278992/143438811-dee7138c-9c85-4808-bc64-c913753913c9.png">

**Comment by craigconstantine** [comment] 2021-11-29 21:05
In an attempt to poke at it more, I decided I'd not mind losing my stats _history_. So I used the plugin section's deactivate and then delete. And then installed the plugin again (search, install, activate from the usual WP plugin directory).

(aside:  I was surprised to see all my historical data remained in place... shouldn't deleting the plugin remove the db tables too?)

THE PROBLEM IS FIXED.  o_O

…no idea why, but now I have all my page stats showing again:

<img width="814" alt="Screen Shot 2021-11-29 at 16 04 26" src="https://user-images.githubusercontent.com/2278992/143942851-b0745dc0-e7b9-4b03-8f97-4e9ce8cb3fdd.png">

**Comment by craigconstantine** [comment] 2021-11-29 21:07
In an effort to keep poking at this, I decided I'd not mind losing all my historical stats... so I delete and installed the plugin.

IT'S FIXED. o_O    ...all my page stats are now showing. So this tells me they were being recorded all along, and there was just something wrong with _display_  —— is it possible there's some setting I flipped off that killed display of the stats, and delete/install reset some config I'd jiggled??

<img width="865" alt="Screen Shot 2021-11-29 at 16 06 00" src="https://user-images.githubusercontent.com/2278992/143943167-9f5749bd-b45d-4bc6-b3cd-60246dbfe276.png">

**Comment by KillianLeroux** [comment] 2021-12-23 12:45
@craigconstantine did you just uninstall and then reinstall the extension? This is what I just did and it didn't work :(

**Comment by craigconstantine** [comment] 2021-12-23 13:16
…yes, that's all I did.

**Comment by jimsihk** [comment] 2022-02-04 20:21
Not sure if there is a fix on this as I have also come across this issue using PHP 7.4.27 with 13.1.15. With WordPress debug mode enabled, below error are shown at the "Page" view page:

> WARNING: wp-content/plugins/wp-statistics/includes/class-wp-statistics-pages.php:407 - Invalid argument supplied for foreach()
>
> do_action('statistics_page_wps_pages_page'), WP_Hook->do_action, WP_Hook->apply_filters, WP_STATISTICS\pages_page::view, WP_STATISTICS\Pages::getTop

Using the Debug Bar plugin, I am able to see below in the Query tab that the plugin is trying to retrieve data from the table wp_statistics_pages.pages. However, I tried to logon my DB, the table does not exist...

> SELECT `pages`.`date`,`pages`.`uri`,`pages`.`id`,`pages`.`type`, SUM(`pages`.`count`) + IFNULL(`historical`.`value`, 0) AS `count_sum` FROM `wp_statistics_pages` `pages` LEFT JOIN `wp_statistics_historical` `historical` ON `pages`.`uri`=`historical`.`uri` AND `historical`.`category`='uri' WHERE (`pages`.`date` BETWEEN '2022-01-06' AND '2022-02-05') GROUP BY `uri` ORDER BY `count_sum` DESC LIMIT 0,10
>
> do_action('statistics_page_wps_pages_page'), WP_Hook->do_action, WP_Hook->apply_filters, WP_STATISTICS\pages_page::view, WP_STATISTICS\Pages::getTop, PDODB->query #54 (0.2 ms)
>
> SELECT COUNT(*) FROM `wp_statistics_pages` `pages` WHERE `date` BETWEEN '2022-01-06' AND '2022-02-05' GROUP BY `uri`
>
> do_action('statistics_page_wps_pages_page'), WP_Hook->do_action, WP_Hook->apply_filters, WP_STATISTICS\pages_page::view, WP_STATISTICS\Pages::TotalCount, PDODB->query

**Comment by mostafasoufi** [comment] 2024-10-12 13:17
I'll close this issue as it is quite old, and the problem has most likely been resolved due to the recent changes made here.

Best

**Closed by mostafasoufi** 2024-10-12 13:17 UTC
Labels: help wanted
