### ISSUE TITLE
Undefined array key warning when running WP-CLI

### ISSUE THREAD

**Issue by derweili** [wp-statistics/wp-statistics#386] opened 2021-12-20 09:47 UTC
When using CLI while this plugin is installed I get this warning:

```
Warning: Undefined array key "HTTP_HOST" in /var/www/wp-content/plugins/wp-statistics/includes/class-wp-statistics-helper.php on line 98
```

The `WP_STATISTICS\Helper::is_login_page()` method tries to get the `HTTP_HOST` from the `$_SERVER` variable which does not exist when using WP-CLI.

I think there should be a check if WP-CLI is running, in this is the case, the plugin should not record any statistics.

**Comment by mostafasoufi** [comment] 2021-12-20 13:27
Thank you for opening the issue, the issue is already fixed in this commit https://github.com/wp-statistics/wp-statistics/commit/c386e0abf03949cf15094d171bf4104c93d5986e but still is not released.

You can fix the issue by getting the changes from the `development` branch until the new version is released.

**Closed by mostafasoufi** 2021-12-20 13:27 UTC
