### ISSUE TITLE
Performance Issues Due to Large Data Volume

### ISSUE THREAD

**Issue by Sinapars** [wp-statistics/wp-statistics#572] opened 2024-10-21 13:08 UTC
Hi team,

I’ve had your plugin installed on several of my websites for over 4 years now. As a result, the data stored in the plugin’s tables has grown significantly, and I’ve noticed some performance slowdowns in various parts of the admin panel, which I’d like to bring to your attention.

For instance, the “Pages” section, where page views are displayed, takes around 16 seconds to fully load. I understand that your suggestion is to delete old data, and I’ve seen this recommendation as a notification within the plugin itself.

However, as you’re well aware, analytics plugins are meant to archive and maintain historical data for review and analysis, so deleting old data isn’t an option for us. We need this information for monthly and yearly comparisons and in-depth analysis.

Do you have any plans to improve the plugin’s performance, particularly for handling large data volumes? For example, optimizing queries, utilizing caching mechanisms, improving table structures and relationships, etc.?

One specific case is the statistics_visitor_relationships table, which holds the most data and still uses the MyISAM engine. Wouldn’t it be better to switch to InnoDB? Also, many of your tables aren’t using the Dynamic Row Format, which could further enhance performance.

Here’s a breakdown of the query execution times in the “Pages” menu:

| Command | Description |
| ---| --- |
| Query | Time |
| SELECT COUNT(visitor.id) as total_visitors FROM wp_statistics_visitor AS visitor INNER JOIN wp_statistics_visitor_relationships AS visitor_relationships ON visitor_relationships.visitor_id = visitor.ID LEFT JOIN wp_statistics_pages AS pages ON visitor_relationships.page_id = pages.page_id LEFT JOIN wp_posts AS posts ON posts.ID = pages.id WHERE DATE(last_counter) BETWEEN '1970-01-01' AND '2024-10-21' AND pages.type IN ('page') AND posts.ID = '1251' | 0.1041 | 
| SELECT COUNT(visitor.id) as total_visitors FROM wp_statistics_visitor AS visitor INNER JOIN wp_statistics_visitor_relationships AS visitor_relationships ON visitor_relationships.visitor_id = visitor.ID LEFT JOIN wp_statistics_pages AS pages ON visitor_relationships.page_id = pages.page_id LEFT JOIN wp_posts AS posts ON posts.ID = pages.id WHERE DATE(last_counter) BETWEEN '1970-01-01' AND '2024-10-21' AND pages.type IN ('home') AND posts.ID = '1116' | 2.3621 |
| SELECT COUNT(visitor.id) as total_visitors FROM wp_statistics_visitor AS visitor INNER JOIN wp_statistics_visitor_relationships AS visitor_relationships ON visitor_relationships.visitor_id = visitor.ID LEFT JOIN wp_statistics_pages AS pages ON visitor_relationships.page_id = pages.page_id LEFT JOIN wp_posts AS posts ON posts.ID = pages.id WHERE DATE(last_counter) BETWEEN '1970-01-01' AND '2024-10-21' AND pages.type IN ('page') AND posts.ID = '259' | 6.0384 |
| SELECT COUNT(visitor.id) as total_visitors FROM wp_statistics_visitor AS visitor INNER JOIN wp_statistics_visitor_relationships AS visitor_relationships ON visitor_relationships.visitor_id = visitor.ID LEFT JOIN wp_statistics_pages AS pages ON visitor_relationships.page_id = pages.page_id LEFT JOIN wp_posts AS posts ON posts.ID = pages.id WHERE DATE(last_counter) BETWEEN '1970-01-01' AND '2024-10-21' AND pages.type IN ('page') AND posts.ID = '1256' | 12.4935 |

And here’s the current data volume of the tables on my site:

statistics_pages: **+210,000**,
statistics_visit: **+1,900**,
statistics_visitor: **+730,000**,
statistics_visitor_relationships: **4 million**

Thank you in advance for your attention and for all your hard work in developing such a great plugin!

Let me know if you need any tweaks!

BR

**Comment by amirfallahii** [comment] 2024-10-21 14:15
Hi @Sinapars 

Thank you for your continued support and for regularly sharing your feedback with us. You've raised several useful issues in the past, and we really appreciate your help in improving WP Statistics

Regarding the issue you mentioned, we’ve just released a minor update, version 14.10.3, about an hour ago. This update includes improvements in the Pages section, which should address the problem you encountered. Please update to the latest version and check if the issue is resolved. Let us know how it goes.

As for your other points, you're right. We've created tasks to improve query performance and overall speed, and we’re planning to address these in versions after 14.11. If you come across any specific areas where heavy queries are slowing things down, please share those with us so we can work on optimizing them. Additionally, it would be helpful if you could provide details about your website environment, such as RAM, CPU, and other relevant specs, to help us replicate the issue more accurately.

Looking forward to hearing from you, and thanks again for your feedback!

Best regards,

**Comment by Sinapars** [comment] 2024-10-21 15:40
Hi @amirfallahii Jan,

Thank you so much for your kind words! I’m really glad to hear that you already have plans in place for optimizing and improving the plugin. 
It’s been a pleasure to share feedback with you in the past, and I’m happy to continue doing so whenever I can help further improve your amazing plugin.

I’ll make sure to send over all the details you requested, such as the server resources and any other relevant information, as soon as possible.

Thanks again for your hard work and for keeping the plugin in great shape!

Best regards,
Sina

**Comment by amirfallahii** [comment] 2024-10-23 09:37
Hi again, @Sinapars,

Thank you for the quick update! We're really glad to hear that the issue with the "Pages" menu has been resolved in version 14.10.3. We also want to apologize for the slowdown caused by the previous version and truly appreciate your patience.

Thanks for sharing your server details and the number of records. This information is very helpful and will allow us to better simulate your environment for future testing and optimizations.

If you encounter any other areas where heavy queries or performance slowdowns occur, don’t hesitate to share those with us. We’re always eager to identify and address any remaining bottlenecks.

Thanks again for your support and detailed feedback, it really helps us move forward with more targeted improvements!

Best regards,

**Closed by amirfallahii** 2024-10-23 09:37 UTC

**Comment by mostafasoufi** [comment] 2024-10-23 09:46
Thank you for reporting and following up on the issue. I’d appreciate any additional information you can provide to help us resolve it quickly.

I would appreciate it if you could share your experience by leaving a [review here](https://wordpress.org/support/plugin/wp-statistics/reviews/?filter=5#new-post).

Best

**Comment by Sinapars** [comment] 2024-10-23 10:01
@amirfallahii 
Thank you so much for the quick response and for the continuous improvements you’re making. 

Since my site has a large volume of data, it can be a helpful real-world environment for testing and improving the plugin’s performance. At a suitable time, I’ll gather information on all sections where I think the load times might be slow or the queries might not be fully optimized, and I’ll update this thread accordingly.

Thanks again for your dedication to improving the plugin. I’m happy to help in any way I can.

@mostafasoufi 
Of course! I think I may have already done that in the past, but I’ll double-check. If I haven’t, I’ll gladly leave a review.

BR

**Comment by Sinapars** [comment] 2024-11-11 12:59
Hi Team,
To improve data display and plugin speed as previously discussed, I’ve noticed that in the latest version (14.11.2), the loading time has significantly increased on certain pages. In version 14.10, the loading delay was less noticeable, but now there are serious issues on the following pages:

**1. Overview Page:**
According to the screenshot below, some AJAX requests are taking over a minute to respond.

- First link (1 min 30 sec):

`/wp-admin/admin-ajax.php?action=wp_statistics_admin_meta_box&ago=&name=top-visitors&wps_nonce=d7eb6a7248&_=1731323144307`

- Second link:

`/wp-admin/admin-ajax.php?action=wp_statistics_admin_meta_box&ago=&name=recent&wps_nonce=d7eb6a7248&_=1731323144308`

- Third link:

`/wp-admin/admin-ajax.php?action=wp_statistics_admin_meta_box&ago=&name=summary&wps_nonce=d7eb6a7248&_=1731323144298
`

![image](https://github.com/user-attachments/assets/37b5c531-3de6-4d9a-be51-18e98761d18c)

**2. Visitor Insights Page:**
Most of the time, this page and its tabs don’t load, or they may eventually load after refreshing several times and waiting for a minute.

- **Visitors Tab:** After several refreshes, it did load, but the query execution times are high.

| Query                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | Rows | Time    |
|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------|---------|
| SELECT visitor.ID, visitor.ip, visitor.platform, visitor.agent, CAST(`visitor`.`version` AS SIGNED) as version, visitor.model, visitor.device, visitor.location, visitor.user_id, visitor.region, visitor.city, visitor.hits, visitor.referred, visitor.last_counter, last_hit.page_id as last_page, last_hit.date as last_view, users.display_name, users.user_email FROM statistics_visitor AS visitor LEFT JOIN (SELECT visitor_relationships.visitor_id, page_id, date FROM statistics_visitor_relationships AS visitor_relationships WHERE (visitor_id, date) IN (SELECT visitor_id, MAX(date) as date FROM statistics_visitor_relationships AS visitor_relationships GROUP BY visitor_id) GROUP BY visitor_id) AS last_hit ON visitor.ID = last_hit.visitor_id LEFT JOIN users AS users ON visitor.user_id = users.ID WHERE DATE(visitor.last_counter) BETWEEN '2024-10-13' AND '2024-11-11' GROUP BY visitor.ID ORDER BY `visitor`.`ID` DESC LIMIT 25 OFFSET 0 | 25   | 57.5109 |

- **Views Tab: Unfortunately, this tab does not load.**

![image](https://github.com/user-attachments/assets/ded2476d-c5ba-46f3-8d0a-aadb03c0be0b)

![image](https://github.com/user-attachments/assets/2b75004b-313f-4dda-bfe5-254a7d91ddb6)


- **Top Visitors Tab: Unfortunately, this tab does not load.**

**3. Page Insights Page:**

- **Contents Tab:** The load time exceeds one minute, with query execution times shown below. 

| Query                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | Rows | Time    |
|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------|---------|
| SELECT posts.ID AS post_id, posts.post_author AS author_id, posts.post_title AS title, posts.post_date AS date, COALESCE(pages.views, 0) AS views, COALESCE(visitors.visitors, 0) AS visitors, COALESCE(comments.total_comments, 0) AS comments, CAST(MAX(CASE WHEN postmeta.meta_key = 'wp_statistics_words_count' THEN postmeta.meta_value ELSE 0 END) AS UNSIGNED) AS words FROM posts AS posts LEFT JOIN (SELECT comment_post_ID, COUNT(comment_ID) AS total_comments FROM comments AS comments WHERE comment_type = 'comment' AND DATE(comment_date) BETWEEN '2024-10-13' AND '2024-11-11' GROUP BY comment_post_ID) AS comments ON posts.ID = comments.comment_post_ID INNER JOIN (SELECT pages.id, SUM(pages.count) AS views FROM statistics_pages AS pages WHERE type IN ('post', 'page', 'kb', 'mkb_faq', 'mkb_glossary', 'home') AND DATE(pages.date) BETWEEN '2024-10-13' AND '2024-11-11' GROUP BY pages.id) AS pages ON posts.ID = pages.id LEFT JOIN (SELECT pages.id as post_id, COUNT(DISTINCT visitor_relationships.visitor_id) AS visitors FROM statistics_visitor_relationships AS visitor_relationships INNER JOIN statistics_pages AS pages ON pages.page_id = visitor_relationships.page_id WHERE type IN ('post', 'page', 'kb', 'mkb_faq', 'mkb_glossary', 'home') AND DATE(visitor_relationships.date) BETWEEN '2024-10-13' AND '2024-11-11' GROUP BY pages.id) AS visitors ON posts.ID = visitors.post_id LEFT JOIN postmeta AS postmeta ON posts.ID = postmeta.post_id WHERE post_type IN ('post', 'page', 'kb', 'mkb_faq', 'mkb_glossary') AND post_status = 'publish' GROUP BY posts.ID ORDER BY `visitors` DESC LIMIT 25 OFFSET 0 | 25   | 17.3680 |

**4. Referrals Page:**

- **Referred Visitors Tab**: Does not load.
- **Referrers and Search Engines Tabs**: These tabs do load, but there are two issues:
- Queries are slow (about 3 seconds) even with no data.
- Pagination is displayed even though there are no records to show. (Screenshot attached)

![image](https://github.com/user-attachments/assets/69d86d08-0673-45af-8664-6e772d3b274e)

**5. Content Analytics Page:**

- **Pages Tab:** Does not load.

**Additional Information:**

1. All issues above were tested multiple times under different conditions.
2. On other sites with less data, pages did load, but performance was still very slow, with high query execution times.
3. Changing the filters on these pages/tabs doesn’t improve the speed. Extending the time range to over a month increases the delay significantly, often resulting in a timeout.
4. High query execution times are also present in other pages and tabs. Although these are lower priority, I can share more details on those as time allows.

Please let me know if you need any more information—I’d be happy to help!

BR,
Sina
@mostafasoufi @amirfallahii

**Comment by navidkashani** [comment] 2024-11-12 04:40
Hi @Sinapars ,

Thank you so much for all the help and feedback you’ve shared with us. Your insights have really helped us improve WP Statistics, and we truly appreciate your support.

As a small thank-you, we’d like to offer you a 100% discount on WP Statistics Premium. If you’re interested, please just say "Hi" to us through [our contact form here](https://wp-statistics.com/contact-us/general-questions/). We’ll send you a coupon code right away.

Thanks again for being such an important part of our community. We look forward to making WP Statistics even better with your help!

Best,  
Navid

**Comment by amirfallahii** [comment] 2024-11-12 14:24
Hi @Sinapars,

Thank you so much for taking the time to provide us with your valuable feedback. We genuinely appreciate your efforts in pointing out the areas that need improvement, as it greatly helps us enhance the WP Statistics plugin.

As you've noticed, due to some existing structural issues in our current database, we've had to rely on complex queries, which unfortunately have impacted the plugin's performance. However, please rest assured that we're fully committed to improving performance and have plans to make significant optimizations in the next couple of major releases.

Specifically, we're aiming to completely overhaul the database structure in version 15, scheduled for release next year. This redesign will not only boost performance but also resolve many of the current issues. That said, since the plugin is actively installed on users' sites, we want to ensure a smooth and safe migration process to the new structure, which requires additional time and testing to get it right.

Regarding the points you raised in your latest message, please be assured that they will be thoroughly reviewed, and we will address them in upcoming versions to enhance your experience with the plugin.

Thank you once again for your continued support and for helping us improve. Your insights are incredibly valuable, and we look forward to your ongoing feedback as we work to make WP Statistics even better.

Best regards,
